"rod_diameter"= 8
"rod_hole_thickness"= 4
"rod_radius"= "rod_diameter" / 2
"platter_diameter"= 320
"platter_radius"= "platter_diameter" / 2
"extruder_mount_hole_spacing"= 75
"arm_rod_spacing"= 40
"top_frame_spacing"= 90
"motor_level_rod_spacing"= 15
"linear_bearing_diameter"= 15
"z_rod_spacing"= 75
"platter_rod_spacing"= 50
"rod_nut_thickness"= 6.5
"rod_nut_inscribed_diameter"= 13
"z_height"= 350
"gear_pitch"=2
"r_gear_teeth"= 450
"theta_gear_teeth"= 385
"sheet_thickness"=5
"sheet_tab_hole_thickness"= "sheet_thickness"
"sheet_tab_width"= "sheet_thickness"*2
"sheet_bolt_diameter"= 3
"sheet_bolt_length"= 16
"sheet_nut_diameter"= 5.5
"sheet_nut_thickness"= 2.5
"sheet_nut_depth"= 10
